# https://jreleaser.org/guide/latest/reference

[signing.pgp]
active = "ALWAYS"
armored = true
mode = "COMMAND"

[deploy.maven.mavenCentral.release-deploy]
active = "RELEASE"
url = "https://central.sonatype.com/api/v1/publisher"
stagingRepositories = ["target/staging-deploy"]
applyMavenCentralRules = true

retryDelay = 20
maxRetries = 102

[release.github]
owner = "manishdait"
name = "maven-release-poc"
skipTag = true
skipRelease = false
overwrite = true

[release.github.update]
enabled = true
sections = ["ASSETS", "BODY"]

[release.github.changelog]
enabled = true
formatted = "ALWAYS"
content = """
    # What's New

    {{changelogChanges}}
    {{changelogContributors}}"""
format = "- {{commitTitle}} by {{contributorUsernameAsLink}} in {{commitAsChanges}}"
contributors.enabled = true

